config/routes.rb
class TaskPointConstraint
  def matches?(request)
    points = request.query_parameters['points']
    (points.blank? || points =~ /^\d+$/)
  end
end

class TaskRankConstraint
  def matches?(request)
    before = request.query_parameters['before']
    after = request.query_parameters['after']
    (before.blank? || before =~ /^\d+$/) && (after.blank? || after =~ /^\d+$/)
  end
end

Tracker::Application.routes.draw do
  devise_for :users

  root to: 'tasks#index'

  resources :features

  resources :projects do
    delete :index, on: :collection
  end

  resources :reference_types
  
  
  resources :stories do
    delete :index, on: :collection
  end

  resources :tasks do
    collection do
      delete :index
      get :print
    end
    member do
      post :advance
      post :block
      post :complete
      post :point, constraints: TaskPointConstraint.new
      post :rank, constraints: TaskRankConstraint.new
      post :unblock
    end
  end

  resources :teams

  resources :users
  
  resources :test if Rails.is_test?

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include FilterHandler
  include ReferencesHandler
  include SortHandler

  DEFAULT_SORT = ['status']
  SORT_FIELDS = ['point', 'status', 'title']

  INDEX_ACTIONS = [:advance, :block, :complete, :create, :destroy, :index, :point, :print, :rank, :unblock, :update]

  load_and_authorize_resource

  before_filter :ensure_initial_state
  before_filter :build_index_query, only: INDEX_ACTIONS

  # GET /tasks
  # GET /tasks.json
  def index
    respond_to do |format|
      format.html { render 'shared/index'}
      format.js { render @filter.errors.empty? ? 'shared/index' : 'shared/filter'; flash.discard }
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @expanded << @task.id if params.has_key?(:expanded)

    respond_to do |format|
      format.html { render template: 'shared/show' }
      format.js { render 'task'; flash.discard }
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @edited << 'new'
    @expanded << 'new'
    
    if @filter.content[:projects].present?
      @task.project_id = @filter.content[:projects].first
    elsif @filter.content[:teams].present?
      team = Team.find(@filter.content[:teams].first) rescue nil
      @task.project_id = team.projects.first.id if team.present? && team.projects.present?
    end
    
    @task.story_id = @filter.content[:stories].first if @filter.content[:stories].present?

    respond_to do |format|
      format.html { render template: 'shared/new' }
      format.js { render 'task'; flash.discard }
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @edited << @task.id
    @expanded << @task.id

    respond_to do |format|
      format.html { render template: 'shared/edit' }
      format.js { render 'task'; flash.discard }
      format.json { render json: @task }
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    respond_to do |format|
      if @task.save
        flash[:notice] = 'Task was successfully created.'
        @changed << @task.id
        
        format.html { redirect_to tasks_path(story_id: @task.story_id) }
        format.js { render 'shared/index'; flash.discard }
        format.json { render json: @task, status: :created, location: @task }
      else
        @edited << 'new'
        @expanded << 'new'
        
        format.html { render action: 'new', template: 'shared/new' }
        format.js { render 'task'; flash.discard }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update_attributes(params[:task])
        flash[:notice] = 'Task was successfully updated.'
        @changed << @task.id

        format.html { redirect_to tasks_path(story_id: @task.story_id) }
        format.js { render 'shared/index'; flash.discard }
        format.json { head :no_content }
      else
        @edited << @task.id
        @expanded << @task.id

        format.html { render action: 'edit', template: 'shared/edit' }
        format.js { render 'task'; flash.discard }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    flash[:notice] = 'Task was successfully deleted.'
    @task.destroy
    
    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.js { render 'shared/index'; flash.discard }
      format.json { head :no_content }
    end
  end
  
  # POST /tasks/1/advance
  def advance
    @task.advance!
    @changed << @task.id

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render 'shared/index'; flash.discard }
      format.json { render json: @tasks }
    end
  end
  
  # POST /tasks/1/block
  def block
    @task.block!
    @changed << @task.id

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render 'shared/index'; flash.discard }
      format.json { render json: @tasks }
    end
  end
  
  # POST /tasks/1/complete
  def complete
    @task.completed!
    @changed << @task.id
    
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render 'shared/index'; flash.discard }
      format.json { render json: @tasks }
    end
  end

  # POST /tasks/1/point?points=xx
  def point
    @expanded << @task.id if params.has_key?(:expanded)

    respond_to do |format|
      if @task.update_attribute(:points, params[:points].to_i)
        flash[:notice] = "Task set to #{view_context.pluralize(@task.points, 'point')}"
        @changed << @task.id

        format.html { redirect_to tasks_path(story_id: @task.story_id) }
        format.js { render 'shared/index'; flash.discard }
        format.json { head :no_content }
      else
        @edited << @task.id

        format.html { render action: "edit" }
        format.js { render 'task'; flash.discard }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tasks/print
  def print
    @iterations = (cookies[:iterations] || '0').split(',').map{|i| i.empty? ? nil : i.to_i}.compact.uniq
    @style = params[:style]
    @style = @style.to_sym if @style.present?
    @style = :cards unless [:cards, :list].include?(@style)

    respond_to do |format|
      format.html { render template: 'shared/print', layout: 'print'}
    end
  end

  # POST /tasks/1/rank?before=xx or /tasks/1/rank?after=xx
  def rank
    @task.rank_between(params[:after], params[:before])
    flash[:notice] = "Unable to move task" unless @task.save

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render 'shared/index'; flash.discard }
      format.json { render json: @tasks }
    end
  end
  
  # POST /tasks/1/unblock
  def unblock
    @task.unblock!
    @changed << @task.id

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render 'shared/index'; flash.discard }
      format.json { render json: @tasks }
    end
  end

  def is_index_action
    INDEX_ACTIONS.include?(action_name.to_sym)
  end

  private

  def build_index_query

    if @filter.content[:group_by] == 'iteration'
      initial_iteration = (params.has_key?(:initial_iteration) ? params[:initial_iteration].to_i : -3) rescue -3
      query = IterationEnumerator.new(Team.find(@filter.content[:teams].first), initial_iteration) rescue nil
    end

    if query.blank?
      @filter.content[:group_by] = nil if @filter.content[:group_by].present?
      
      query = @tasks || Task

      projects = @filter.content[:projects]
      features = @filter.content[:features]
      status = @filter.content[:status]
      stories = @filter.content[:stories]
      teams = @filter.content[:teams]

      query = query.in_state(status) if status.present?

      query = query.for_features(features) if features.present?
      query = query.for_projects(projects) if projects.present?
      query = query.for_stories(stories) if stories.present?

      query = query.for_teams(teams) if teams.present?
      
      query = query.at_least_points(@filter.content[:min_points]) if @filter.content[:min_points] =~ /0|1|2|3|4|5/
      query = query.no_more_points(@filter.content[:max_points]) if @filter.content[:max_points] =~ /0|1|2|3|4|5/

      @sort.each do |sort|
        case sort
        when 'point' then query = query.in_point_order('ASC')
        when '-point' then query = query.in_point_order('DESC')
        when 'status' then query = query.in_iteration_order('ASC')
        when '-status' then query = query.in_iteration_order('DESC')
        when 'title' then query = query.in_title_order('ASC')
        when '-title' then query = query.in_title_order('DESC')
        end
      end

      query = query.includes(:feature, :project, :references).uniq
    end

    @tasks = query
  end

  def ensure_initial_state
    @changed = []
    @edited = []
    @expanded = []
    @iterations = [0]
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

  def points_to_class(points)
    case points
    when 0, nil then 'zero-points'
    when 1 then 'one-point'
    when 2 then 'two-points'
    when 3 then 'three-points'
    when 5 then 'five-points'
    when 8 then 'eight-points'
    end
  end

end

app/views/tasks/_add_menu.html.haml
%ul.dropdown
  %li= link_to I18n.t(:new, scope: [:controllers, :tasks]), new_task_path
  %li= link_to I18n.t(:new_story, scope: [:controllers, :tasks]), new_task_path(story:true)

app/views/tasks/_edit.html.haml
- remote = false if remote.nil?
- stand_alone = true if stand_alone.nil?
- task ||= @task

%div{class: stand_alone ? 'task edit-mode' : nil}
  = form_for task, remote:remote do |f|
    = f.hidden_field :points
    .row-fluid
      .span12
        .clearfix{class: task.status}
          
          - if task.errors.any?
            .row-fluid
              .span12
                #error_explanation
                  %h2= "#{pluralize(task.errors.count, "error")} prohibited this task from being saved:"
                  %ul
                    - task.errors.full_messages.each do |msg|
                      %li= msg

          .row-fluid.section
            .controls.controls-row
              .span9
                = f.label :title
                = f.text_field :title, placeholder: 'Enter task title', class: 'span12', autofocus: true
              .span3
                = f.label :status
                = flat_select_tag 'task[status]', options_for_select(Task::ALL_STATES.map{|t| [I18n.t(t, scope: [:activerecord, :labels, :task]), t]}, task.status), {data: {status_select: true}}
                = f.label :blocked do
                  = f.check_box :blocked
                  = t(:blocked, scope: [:activerecord, :labels, :task])


          .row-fluid.section
            .controls.controls-row
              .span9
                = f.label :story_id
                = flat_select_tag 'task[story_id]', options_for_select(Story.all_stories, task.story_id)
              .span3.start_date{style: "display:#{task.in_progress? ? 'inline-block' : 'none'}"}
                = f.label :start_date
                = f.text_field :start_date, data: {datefield: true}, class: 'span12', type: 'datetime'
              .span3.completed_date{style: "display:#{task.completed? ? 'inline-block' : 'none'}"}
                = f.label :completed_date
                = f.text_field :completed_date, data: {datefield: true}, class: 'span12', type: 'datetime'

          .row-fluid.section
            .span12
              = f.label :description, t(:description, scope: [:activerecord, :attributes, :task])
              = f.text_area :description, rows: 5, placeholder: 'Provide a description or details', class: 'span12'

          / .row-fluid.section
          /   .span12
          /     = f.label :tag_list, t(:tag_list, scope: [:activerecord, :attributes, :task])
          /     = f.text_field :tag_list, class: 'span12'

          .row-fluid.section
            .span12
              = render partial: 'shared/edit_references', locals: {references: task.references, referent_type: :task}

          .row-fluid.section
            .span4
              = f.label :project_id, t(:project, scope: [:activerecord, :attributes, :task])
              = flat_select_tag 'task[project_id]', options_for_select(Project.in_name_order.all.collect{|p| [ p.name, p.id ]}, task.project_id)
            .span3.offset1
              = f.label :points, t(:points, scope: [:activerecord, :attributes, :task])
              = render partial: 'points', locals: {task: task, editable: true}

          .row-fluid
            .span4
              = f.label :category, t(:category, scope: [:activerecord, :attributes, :task])
              = flat_select_tag 'task[category]', options_for_select(Task.all_categories, task.category), data:{task_category: true}

          .row-fluid
            .span6.offset6.text-right
              = f.submit 'Save', class: 'btn btn-small btn-flat btn-primary'
              \|
              - if can? :destroy, task
                - unless task.new_record?
                  = link_to 'Delete', task, method: :delete, class: 'btn btn-small btn-flat btn-danger', data: { confirm: "WARNING: Are you sure you want to delete this task?" }, remote:remote
                  \|
              = link_to 'Cancel', task.new_record? ? tasks_path : task_path(task), class: 'btn btn-small btn-link', remote:remote
          = render template: 'shared/bind_dates'

app/views/tasks/_filter.html.haml
- content = @filter.content || {}
- classes = []
- classes << 'visible' if !@filter.errors.empty? || params[:show]

#Filter{data: {filter: 1}, class: classes}
  .filter-container
    = form_for @filter, url: tasks_path, method: :get, remote: true do |f|
      = f.hidden_field :id
      = f.hidden_field :area

      - if @filter.errors.any?
        .row-fluid
          .span12
            #error_explanation
              %h2= "#{pluralize(@filter.errors.count, "error")} prohibited this filter from being saved:"
              %ul
                - @filter.errors.full_messages.each do |msg|
                  %li= msg
      
      .row-fluid.section
        .span8
          = f.label :name
          = f.text_field :name, class: 'span12'
        / - if current_user.role? :scrum_master
        /   .span4
        /     = f.label :user_id
        /     = flat_select_tag 'filter[user_id]', options_for_select(User.all_users, @filter.user_id)
      
      .row-fluid.section
        .span12
          %label.checkbox{for: 'filter_content_group_by'}
            = check_box_tag 'filter[content][group_by]', 1, content[:group_by] == 'iteration', data: {group_by: :iteration}
            = 'Group tasks by iteration'

      .row-fluid.section
        .controls.controls-row
          .span4
            = label_tag 'filter_content_status', 'Status'
            = flat_select_tag 'filter[content][status]', options_for_select(StatusScopes.all_states, StatusScopes.collapse(content[:status]))
          .span4
            = label_tag 'filter_content_teams', 'Team'
            = flat_select_tag 'filter[content][teams]', options_for_select(Team.all_teams, content[:teams] || '')
          .span4
            = label_tag 'filter_content_projects', 'Projects'
            = flat_select_tag 'filter[content][projects]', options_for_select(Project.all_projects, content[:projects] || '')

      .row-fluid.section.task-filter{class: content[:group_by] ? 'hidden' : nil}
        .controls.controls-row
          .span4.multi-select
            = label_tag 'filter_content_features', 'Features'
            = select_tag 'filter[content][features]', options_for_select(Feature.all_features, content[:features] || ''), multiple: true
          .span4.multi-select
            = label_tag 'filter_content_stories', 'Stories'
            = select_tag 'filter[content][stories]', options_for_select(Story.all_stories, content[:stories] || ''), multiple: true
          .span4
            .row-fluid
              .span8
                = label_tag 'filter_content_min_points', 'Minimum Points'
                = flat_select_tag 'filter[content][min_points]', options_for_select(Task.all_points, content[:min_points])
                = label_tag 'filter_content_max_points', 'Maximum Points'
                = flat_select_tag 'filter[content][max_points]', options_for_select(Task.all_points, content[:max_points])

      .row-fluid
        .span5.offset7.text-right
          = submit_tag 'Apply', name: :apply, class: 'btn btn-small btn-flat btn-primary'
          - if @filter.new_record?
            \|
            = submit_tag 'Save', name: :commit_filter, class: 'btn btn-small btn-flat btn-info'
          - else
            \|
            = submit_tag 'Update', name: :commit_filter, class: 'btn btn-small btn-flat btn-info'
            \|
            = link_to 'Delete', tasks_path(destroy: true), method: :delete, data: { confirm: "#{t(:warning_html, scope: :filter)}" }, remote: true, class: 'btn btn-small btn-flat btn-danger'
          \|
          = link_to 'Close', 'javascript:void();', data: {filter_close: true}, class: 'btn btn-small btn-link'

app/views/tasks/_points.html.haml
- possible_points = Task::POINTS[1,Task::POINTS.length]
- editable = true if editable.nil?
- task ||= @task

- if editable
  .points.editable><
    .overlay{class: points_to_class(task.points)}><
      - possible_points.each do |points|
        %span.badge.badge-inverse{data: {points: points}}><= points
    - possible_points.each do |points|
      %span.badge{data: {points: points}}><= points
- else
  .points><
    - possible_points.each do |points|
      %span.badge{class: task.points >= points ? 'badge-inverse' : nil, data: {points: points}}><= points

app/views/tasks/_show.html.haml
- task ||= @task
- description = task.description.present? ? task.description : t(:no_details_html, scope: [:activerecord, :labels, :task])

= render partial: 'task', locals: {expanded: [task.id], stand_alone: true}
.row-fluid
  .span6.offset6.text-right
    - if can? :edit, task
      = link_to 'Edit', edit_task_path(task), class: 'btn btn-small btn-flat btn-primary'
      \|
    - if can? :destroy, task
      = link_to 'Delete', task, method: :delete, data: { confirm: "WARNING: Are you sure you want to delete this task?" }, class: 'btn btn-small btn-flat btn-danger'
      \|
    = link_to 'Back', tasks_path, class: 'btn btn-small btn-link'

app/views/tasks/_task.html.haml
- edited ||= []
- expanded ||= []
- printing = false if printing.nil?
- stand_alone = printing if stand_alone.nil?
- style = :cards if style.nil?
- task ||= @task
- options = {remote: true}
- options[:disabled] = 'disabled' if task.completed?
- id = task.new_record? ? 'new' : task.id
- classes = 'task '
- classes << style.to_s if printing
- classes << ' edit-mode' if @edited.include?(id)
- data = {expanded: @expanded.include?(id) ? 1 : 0}
- data[:status] = task.status
- data[:blocked] = 1 if task.blocked?
- data[:print] = 1 if printing
- data[:draggable] = 1 if task.pending? && can?(:drag, task)
- data[task.category.to_sym] = 1
- row_classes = @expanded.include?(id) || stand_alone ? 'expanded' : 'compact'
- show_rank = false if show_rank.nil?

= content_tag stand_alone ? 'div' : 'li', {id: "Task_#{id}", class: classes, data: data} do
  - if printing
    - if style == :cards
      .row-fluid
        .span12
          .title= task.to_s
      .row-fluid
        .span8
          .project= "#{task.project.name} &mdash; #{pluralize(task.points, 'Point')}".html_safe
        .span4.text-right
          = t(task.status, scope: [:activerecord, :labels, :task])
      .row-fluid
        .span12
          .description= task.description
      .row-fluid
        .span12
          .footer
            .row-fluid
              .span6
                - if task.story.present? && task.story.references.present?
                  .contact-us= "#{task.story.references.first}"
              .span6
                - if iteration.present?
                  .release-date= iteration.end_date.to_date.to_s(:yy_mm_dd)
    - else
      .row-fluid
        .span8
          .title= task.to_s
        .span4.text-right
          = "#{pluralize(task.points, 'Point')} &mdash; #{t(task.status, scope: [:activerecord, :labels, :task])}".html_safe
      .row-fluid
        .span8
          .project= task.project.name
        .span4.text-right
          - if task.story.present? && task.story.references.present?
            .contact-us= "#{task.story.references.first}"
      - if task.description.present?
        .row-fluid
          .span12
            .description= task.description


  - else
    .row{class: row_classes}
      .span8

        - if edited.include?(id)
          = render partial: 'edit', locals: {task:task, remote:true, stand_alone: false}

        - elsif expanded.include?(id)
          %form
            .row-fluid
              .span12
                .clearfix{class: task.status}
                  .row-fluid.section
                    .span8
                      %label= 'Title'
                      .title= task.title
                    .span4
                      %div{style:'display:inline-block;'}
                        %label= 'Status'
                        .title
                          = t(task.status, scope: [:activerecord, :labels, :task])
                          - if task.blocked?
                            .blocked= t(:blocked, scope: [:activerecord, :attributes, :task])
                      .command-block{class: stand_alone ? 'hidden' : nil}
                        - if can? :destroy, task
                          = awesome_link_to '', task_path(task), glyph: 'awesome-remove', data: {confirm: "WARNING: Are you sure you want to delete this task?", method: :delete}, remote: true
                        - if can? :edit, task
                          = awesome_link_to '', edit_task_path(task), glyph: 'awesome-edit', remote:true
                        = awesome_link_to '', task_path(task), glyph: 'awesome-eye-close', remote:true
                  - if task.story.present?
                    .row-fluid.section
                      .span12
                        %label= 'Story'
                        .title
                          = link_to task.story.to_s, story_path(task.story.id)
                        = render partial: 'shared/show_references', locals:{references: task.story.references}
                  - if task.description.present?
                    .row-fluid.section
                      .span12
                        %label= 'Description'
                        .description= task.description
                  / - if task.tag_list.present?
                  /   .row-fluid.section
                  /     .span12
                  /       %label= 'Tags'
                  /       .tags= task.tag_list
                  - if task.references.present?
                    .row-fluid.section
                      .span12
                        %label= 'References'
                        = render partial: 'shared/show_references', locals:{references: task.references}
                  .row-fluid
                    .span5
                      %label= 'Project'
                      .project= task.project.name
                    .span2
                      - if task.development?
                        %label= 'Points'
                        - cache action: :index, action_suffix: "points-#{task.points}-#{can?(:edit, task)}" do
                          = render partial: 'points', locals: {task: task, editable: can?(:edit, task)}
                    .span3.offset1
                      - if task.story.present? && task.story.release_date.present?
                        %label= 'Release Date'
                        .release-date{data: {date_status: task.story.release_date_status}}
                          =task.story.release_date.to_date.to_s(:yy_mm_dd)
                      - else
                        %label= '&nbsp;'.html_safe
                        .release-date= '&nbsp;'.html_safe
                  .row-fluid
                    .span5
                      %label= 'Category'
                      .category
                        = t(task.category, scope: [:activerecord, :labels, :task])

        - else
          .row-fluid
            .span12
              .clearfix{class: task.status}
                .row-fluid
                  .span5
                    .title= task.story.present? ? link_to(task.to_s, story_path(task.story.id)) : task.to_s
                  .span2
                    - if task.development?
                      - cache action: :index, action_suffix: "points-#{task.points}-#{can?(:edit, task)}" do
                        = render partial: 'points', locals: {task: task, editable: can?(:edit, task)}
                    - if show_rank
                      = task.rank
                  .span1
                    .project= task.project.name
                  - if task.story.present? && task.story.release_date.present?
                    .span2
                      .release-date{data: {date_status: task.story.release_date_status}}
                        =task.story.release_date.to_date.to_s(:yy_mm_dd)
                  .span2.text-right
                    .command-block.on-hover
                      - if task.incomplete?
                        / - if task.blocked? && can?(:unblock, task)
                        /   = awesome_button_to 'Unblock', url_for(controller: :tasks, action: :unblock, id: task.id), options.merge(glyph: 'awesome-circle-blank')
                        / - if !task.blocked? && can?(:block, task)
                        /   = awesome_button_to 'Block', url_for(controller: :tasks, action: :block, id: task.id), options.merge(glyph: 'awesome-ban-circle')
                        - if can? :advance, task
                          = awesome_button_to 'Advance', url_for(controller: :tasks, action: :advance, id: task.id), options.merge(glyph: 'awesome-ok')
                      - if can? :edit, task
                        = awesome_link_to '', edit_task_path(task), glyph: 'awesome-edit', remote:true
                      = awesome_link_to '', task_path(task, expanded: 1), glyph: 'awesome-eye-open', remote:true

app/views/tasks/_task_cards.html.haml
- iteration = nil unless defined?(iteration)
- tasks = [] if tasks.nil?

- tasks.each_slice(2) do |row_tasks|
  .row.tasks
    .span5= render partial: 'task', locals: {task: row_tasks.first, printing: true, iteration: iteration}
    .span5.offset1= render partial: 'task', locals: {task: row_tasks.last, printing: true, iteration: iteration} if row_tasks.length > 1

app/views/tasks/_task_list.html.haml
- iteration = nil unless defined?(iteration)
- tasks = [] if tasks.nil?

- tasks.each do |task|
  .row
    .span12
      = render partial: 'task', locals: {task: task, printing: true, iteration: iteration, style: :list}

app/views/tasks/_tasks.html.haml
- if @tasks.is_a?(IterationEnumerator)
  - projects = @filter.content[:projects] || @tasks.team.projects.map{|p| p.id}
  - states = @filter.content[:status] || StatusScopes::ALL_STATES
- printing = false if printing.nil?
- show_rank = params.has_key?(:rank)

#Main
  - unless printing
    = render 'layouts/messages'
    = render 'shared/overview'

  - if printing
    - task_style = @style == :list ? 'task_list' : 'task_cards'
    - if @tasks.is_a?(IterationEnumerator)
      - @tasks.each_iteration(-2) do |iteration|
        - next unless @iterations.include?(iteration.number)
        - unless @iterations.length <= 1
          .iteration-open= "Iteration Ending &mdash; #{iteration.end_date.to_formatted_s(:medium)}".html_safe
        - tasks = iteration.tasks.find_all{|task| states.include?(task.status) && projects.include?(task.project.id)}
        = render partial: task_style, locals: {tasks: tasks, iteration: iteration}
        - unless @iterations.length <= 1
          .iteration-close
            &nbsp;

    - else
      = render partial: task_style, locals: {tasks: @tasks}

  - else
    - if @tasks.is_a?(IterationEnumerator)
      - @tasks.each_iteration do |iteration|
        .iteration-marker{data: {iteration: iteration.number.to_s, collapsed: 0}}
          .row.iteration-toggle
            .glyphicon.collapse_top
            .span2
              .date
                = iteration.start_date.to_formatted_s(:yy_mm_dd)
                &ndash;
                = iteration.end_date.to_formatted_s(:yy_mm_dd)
            .span3
              %span.badge.badge-inverse= iteration.points
              \|
              %span.badge.badge-success= iteration.completed
              %span.badge.badge-info= iteration.in_progress
              %span.badge.badge-important= iteration.pending
              - if iteration.blocked > 0
                \|
                %span.badge.badge-warning= iteration.blocked
        
        %ol.unstyled.task-list{data: {iteration: iteration.number}}<
          - tasks = iteration.tasks.find_all{|task| states.include?(task.status) && projects.include?(task.project.id)}
          - if tasks.count > 0
            = render partial: 'task', collection: tasks, locals: {edited: @edited, expanded: @expanded, show_rank: show_rank}
          - else
            %li{data: {iteration: iteration.number, collapsed: 0, empty: 1}}
              %h3.subheader= t(:none_html, scope: [:controllers, :tasks])

      %div
        :javascript
          $(function() {$('body').trigger('iteration.visibility');});

    - else
      .task-sort
        %table.table
          %thead
            %tr
              = render partial: 'shared/sortable', locals: {name: 'Title', field: 'title', classes: 'span5'}
              = render partial: 'shared/sortable', locals: {name: 'Points', field: 'point', classes: 'span3'}
              = render partial: 'shared/sortable', locals: {name: 'Status', field: 'status', classes: 'span4 last'}

        %ol.unstyled.task-list<
          - if @tasks.count > 0
            = render partial: 'task', collection: @tasks, locals: {edited: @edited, expanded: @expanded, show_rank: show_rank}
          - else
            %li{data: {collapsed: 0, empty: 1}}
              %h3.subheader= t(:none_html, scope: [:controllers, :tasks])

    - if can? :drag, Task
      = render template: 'shared/bind_list'

app/views/tasks/delete.js.erb
$('#Task_<%= @task.id%>').remove();
<%= render template: 'shared/messages' unless flash.empty? %>
<%= render template: 'shared/reset_transients' %>

app/views/tasks/task.js.erb
<%
content = escape_javascript(render(partial: @task, locals: {edited: @edited, expanded: @expanded}))
id = @task.new_record? ? 'new' : @task.id
%>
if ($('#Task_<%= id %>').length > 0) {
  $('#Task_<%= id%>').replaceWith('<%= content %>');
} else if ($('.task-list > li').length > 0) {
  var e = $(".task-list > li[data-status='pending']");
  if (e.length <= 0) {
    e = $('.task-list > li');
  }
  e.first().before('<%= content %>');
  $('.task-list > li[data-empty]').remove();
}
<% if @changed.include?(id) %>
$('#Task_<%= id%>').effect('highlight',{duration: 750});
<% end %>
<%= render 'shared/messages' unless flash.empty? %>
<%= render 'shared/reset_transients' %>