config/routes.rb
class TaskPointConstraint
  def matches?(request)
    points = request.query_parameters['points']
    (points.blank? || points =~ /^\d+$/)
  end
end

class TaskRankConstraint
  def matches?(request)
    before = request.query_parameters['before']
    after = request.query_parameters['after']
    (before.blank? || before =~ /^\d+$/) && (after.blank? || after =~ /^\d+$/)
  end
end

Tracker::Application.routes.draw do
  devise_for :users

  root to: 'tasks#index'

  resources :features

  resources :projects do
    delete :index, on: :collection
  end

  resources :reference_types
  
  
  resources :stories do
    delete :index, on: :collection
  end

  resources :tasks do
    collection do
      delete :index
      get :print
    end
    member do
      post :advance
      post :block
      post :complete
      post :point, constraints: TaskPointConstraint.new
      post :rank, constraints: TaskRankConstraint.new
      post :unblock
    end
  end

  resources :teams

  resources :users
  
  resources :test if Rails.is_test?

end

app/controllers/reference_types_controller.rb
class ReferenceTypesController < ApplicationController
  include FilterHandler
  include SortHandler

  DEFAULT_SORT = ['name']
  SORT_FIELDS = ['name']
  INDEX_ACTIONS = [:create, :destroy, :index, :update]

  load_and_authorize_resource

  before_filter :ensure_initial_state
  before_filter :build_index_query, only: INDEX_ACTIONS

  # GET /reference_types
  # GET /reference_types.json
  def index
    respond_to do |format|
      format.html { render 'shared/index'}
      format.js { render @filter.errors.empty? ? 'shared/index' : 'filter' }
      format.json { render json: @reference_types }
    end
  end

  # GET /reference_types/1
  # GET /reference_types/1.json
  def show
    @expanded << @reference_type.id if params.has_key?(:expanded)

    respond_to do |format|
      format.html { render template: 'shared/show' }
      format.js { render 'reference_type' }
      format.json { render json: @reference_type }
    end
  end

  # GET /reference_types/new
  # GET /reference_types/new.json
  def new
    @edited << 'new'
    @expanded << 'new'

    respond_to do |format|
      format.html { render template: 'shared/new' }
      format.js { render 'reference_type' }
      format.json { render json: @reference_type }
    end
  end

  # GET /reference_types/1/edit
  def edit
    @edited << @reference_type.id
    @expanded << @reference_type.id

    respond_to do |format|
      format.html { render template: 'shared/edit' }
      format.js { render 'reference_type' }
      format.json { render json: @reference_type }
    end
  end

  # POST /reference_types
  # POST /reference_types.json
  def create
    respond_to do |format|
      if @reference_type.save
        flash[:notice] = 'Reference type was successfully created.'
        @changed << @reference_type.id
        
        format.html { redirect_to reference_types_path }
        format.js { render 'shared/index'; flash.discard }
        format.json { render json: @reference_type, status: :created, location: @reference_type }
      else
        @edited << 'new'
        @expanded << 'new'

        format.html { render action: 'new', template: 'shared/new' }
        format.js { render 'reference_type' }
        format.json { render json: @reference_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reference_types/1
  # PUT /reference_types/1.json
  def update
    respond_to do |format|
      if @reference_type.update_attributes(params[:reference_type])
        flash[:notice] = 'Reference type was successfully updated.'
        @changed << @reference_type.id

        format.html { redirect_to reference_types_path }
        format.js { render 'shared/index'; flash.discard }
        format.json { head :no_content }
      else
        @edited << @reference_type.id
        @expanded << @reference_type.id

        format.html { render action: 'edit', template: 'shared/edit' }
        format.js { render 'reference_type' }
        format.json { render json: @reference_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reference_types/1
  # DELETE /reference_types/1.json
  def destroy
    @reference_type.destroy

    flash[:notice] = 'Reference type was successfully deleted.'

    respond_to do |format|
      format.html { redirect_to reference_types_path }
      format.js { render 'shared/index'; flash.discard }
      format.json { head :no_content }
    end
  end


  def is_index_action
    INDEX_ACTIONS.include?(action_name.to_sym)
  end

  private

  def build_index_query
    query = @reference_types || ReferenceType

    @sort.each do |sort|
      case sort
      when '-name' then query = query.in_name_order('DESC')
      when 'name' then query = query.in_name_order('ASC')
      end
    end

    @reference_types = query
  end

  def ensure_initial_state
    @edited = []
    @expanded = []
    @changed = []
  end

end

app/views/reference_types/_edit.html.haml
- reference_type ||= @reference_type
- remote = false if remote.nil?
- stand_alone = true if stand_alone.nil?

= content_tag stand_alone ? 'div' : 'td', stand_alone ? {} : {colspan: 2} do
  = form_for reference_type, remote:remote do |f|
    .row-fluid
      .span12
        - if reference_type.errors.any?
          .row-fluid
            .span12
              #error_explanation
                %h2= "#{pluralize(reference_type.errors.count, "error")} prohibited this reference type from being saved:"
                %ul
                  - reference_type.errors.full_messages.each do |msg|
                    %li= msg

        .row-fluid.section
          .span5
            = f.label :name
            = f.text_field :name, class: 'span12'
          .span5
            = f.label :deprecated do
              = f.check_box :deprecated
              = t(:deprecated, scope: [:activerecord, :labels, :reference_type])

        .row-fluid.section
          .span11
            = f.label :url_pattern do
              URL Pattern
              %span.note= "(All instances of <span class='reference-type-value'>#{ReferenceType::VALUE_MARKER}</span> will be replaced with the reference value)".html_safe
            = f.url_field :url_pattern, class: 'span12'

        .row-fluid.section
          .span11
            = f.label :tip
            = f.text_field :tip, class: 'span12'
        
        .row
          .span4.offset8.text-right
            = f.submit 'Save', class: 'btn btn-small btn-flat btn-primary'
            \|
            = link_to 'Delete', reference_type, method: :delete, data:{confirm: "WARNING: Are you sure you want to delete this reference type?" }, remote:remote, class: 'btn btn-small btn-flat btn-danger'
            \|
            = link_to 'Cancel', reference_type.new_record? ? reference_types_path : reference_type_path(reference_type), remote:remote, class: 'btn btn-small btn-flat btn-link'

app/views/reference_types/_reference_type.html.haml
- edited ||= []
- expanded ||= []
- reference_type ||= @reference_type
- id = reference_type.new_record? ? 'new' : reference_type.id

- if edited.include?(id)
  %tr.reference-type.edit-mode.expanded#ReferenceType{id: id, data: {expanded: 1, deprecated: reference_type.deprecated}}
    = render partial: 'edit', locals:{reference_type:reference_type, remote:true, stand_alone:false}

- else
  %tr.reference-type.compact#ReferenceType{id: id, data: {deprecated: reference_type.deprecated}}
    = render partial: 'show', locals:{reference_type:reference_type, remote:true, stand_alone:false}

app/views/reference_types/_reference_types.html.haml
#Main
  = render 'layouts/messages'
  = render 'shared/overview'

  %table.table.reference-type-list#ReferenceTypeList
    %thead
      %tr
        =render partial: 'shared/sortable', locals: {name: 'Name', field: 'name', classes: 'span3'}
        %th.span9= 'URL Pattern'

    %tbody
      - if @reference_types.empty?
        %tr.reference-type#ReferenceType_new
          %td{colspan: 2}
            %h3.subheader= t(:none_html, scope: [:controllers, :reference_types])
      - else
        = render partial: 'reference_type', collection: @reference_types, locals: {edited: @edited, expanded: @expanded}

app/views/reference_types/_show.html.haml
- open = "<span class='reference-type-value'>"
- close = "</span>"
- reference_type ||= @reference_type
- remote = false if remote.nil?
- stand_alone = true if stand_alone.nil?

- if stand_alone
  .reference-type.expanded
    .row-fluid
      .span5= reference_type.name
      .span5= reference_type.highlight_url_pattern(open, close).html_safe
    .row-fluid
      .spanb4.offset8.text-right
        = link_to 'Edit', edit_reference_type_path(reference_type), remote:remote, class: 'btn btn-small btn-flat btn-primary'
        \|
        = link_to 'Delete', reference_type, method: :delete, data: { confirm: "WARNING: Are you sure you want to delete this reference type?" }, remote:remote, class: 'btn btn-small btn-flat btn-danger'
        \|
        = link_to 'Back', reference_types_path, class: 'btn btn-small btn-flat btn-link'

- else
  %td= reference_type.name
  %td
    = reference_type.highlight_url_pattern(open, close).html_safe
    .command-block.on-hover<
      = awesome_link_to '', edit_reference_type_path(reference_type), glyph: 'awesome-edit', remote:true

app/views/reference_types/reference_type.js.erb
<%
content = escape_javascript(render(partial: @reference_type, locals: {edited: @edited, expanded: @expanded}))
id = @reference_type.new_record? ? 'new' : @reference_type.id
%>
if ($('#ReferenceType_<%= id %>').length > 0) {
  $('#ReferenceType_<%= id%>').replaceWith('<%= content %>');
} else if ($('.reference-type-list > tbody > tr').length > 0) {
  $('.reference-type-list > tbody > tr').first().before('<%= content %>');
  $('.reference-type-list > tbody > tr[data-empty]').remove();
}
<% if @changed.include?(id) %>
$('#ReferenceType_<%= id%>').effect('highlight',{duration: 750});
<% end %>
<%= render 'shared/messages' unless flash.empty? %>
<%= render 'shared/reset_transients' %>