config/routes.rb
class TaskPointConstraint
  def matches?(request)
    points = request.query_parameters['points']
    (points.blank? || points =~ /^\d+$/)
  end
end

class TaskRankConstraint
  def matches?(request)
    before = request.query_parameters['before']
    after = request.query_parameters['after']
    (before.blank? || before =~ /^\d+$/) && (after.blank? || after =~ /^\d+$/)
  end
end

Tracker::Application.routes.draw do
  devise_for :users

  root to: 'tasks#index'

  resources :features

  resources :projects do
    delete :index, on: :collection
  end

  resources :reference_types
  
  
  resources :stories do
    delete :index, on: :collection
  end

  resources :tasks do
    collection do
      delete :index
      get :print
    end
    member do
      post :advance
      post :block
      post :complete
      post :point, constraints: TaskPointConstraint.new
      post :rank, constraints: TaskRankConstraint.new
      post :unblock
    end
  end

  resources :teams

  resources :users
  
  resources :test if Rails.is_test?

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  team_id    :integer
#  start_date :datetime
#  end_date   :datetime
#

class Project < ActiveRecord::Base
  include CacheCleanser
  
  attr_accessible :end_date, :name, :features, :feature_projects, :feature_projects_attributes, :start_date

  belongs_to :team

  has_many :feature_projects, dependent: :destroy
  has_many :features, through: :feature_projects

  has_many :tasks, dependent: :destroy
  has_many :stories, through: :tasks

  accepts_nested_attributes_for :feature_projects, allow_destroy: true

  after_create :ensure_features
  before_validation :ensure_start_date
  
  validates_presence_of :name
  validates_presence_of :start_date
  
  scope :with_name, lambda {|name| where(name: name) }

  scope :supported, lambda{where('projects.start_date <= :date AND (projects.end_date IS NULL OR projects.end_date > :date)', date: Time.now)}
  scope :started_on_or_before, lambda{|date| where("projects.start_date <= ?", date)}

  scope :for_team, lambda{|team| where(team_id: (team.is_a?(Team) ? team.id : team))}

  scope :in_name_order, lambda{|dir = 'ASC'| order("projects.name #{dir}")}

  class<<self
    def active
      @active ||= self.in_name_order.all
    end

    def all_projects
      @all_projects ||= [['-', '']] + Project.active.map{|project| [project.name, project.id]}.uniq
    end
    
    def refresh_cache
      @active = nil
      @all_projects = nil
    end
  end

  def is_feature?(status, feature)
    feature_project = self.feature_projects.for_feature(feature).first
    (status == 'unsupported' && feature_project.blank?) || (feature_project.present? && feature_project.in_state?(status))
  end

  private

  def ensure_features
    FeatureProject.ensure_project_features(self)
  end

  def ensure_start_date
    self.start_date ||= DateTime.parse('2012-12-01')
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include FilterHandler

  INDEX_ACTIONS = [:create, :destroy, :index, :update]

  before_filter :ensure_features

  load_and_authorize_resource

  before_filter :ensure_initial_state
  before_filter :build_index_query, only: INDEX_ACTIONS

  # GET /projects
  # GET /projects.json
  def index
    respond_to do |format|
      format.html { render 'shared/index'}
      format.js { render @filter.errors.empty? ? 'shared/index' : 'filter' }
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @expanded << @project.id if params.has_key?(:expanded)

    respond_to do |format|
      format.html { render template: 'shared/show' }
      format.js { render 'project' }
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @edited << 'new'
    @expanded << 'new'

    respond_to do |format|
      format.html { render template: 'shared/new' }
      format.js { render 'project' }
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @edited << @project.id
    @expanded << @project.id

    respond_to do |format|
      format.html { render template: 'shared/edit' }
      format.js { render 'project' }
      format.json { render json: @project }
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    respond_to do |format|
      if @project.save
        flash[:notice] = 'Project was successfully created.'
        @changed << @project.id
        
        format.html { redirect_to projects_path }
        format.js { render 'shared/index'; flash.discard }
        format.json { render json: @project, status: :created, location: @project }
      else
        @edited << 'new'
        @expanded << 'new'

        format.html { render action: 'new', template: 'shared/new' }
        format.js { render 'project' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        flash[:notice] = 'Project was successfully updated.'
        @changed << @project.id

        format.html { redirect_to projects_path }
        format.js { render 'shared/index'; flash.discard }
        format.json { head :no_content }
      else
        @edited << @project.id
        @expanded << @project.id

        format.html { render action: 'edit', template: 'shared/edit' }
        format.js { render 'project' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy

    flash[:notice] = 'Project was successfully deleted.'

    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js { render 'shared/index'; flash.discard }
      format.json { head :no_content }
    end
  end

  def is_index_action
    INDEX_ACTIONS.include?(action_name.to_sym)
  end

  private

  def build_index_query
    query = @projects || Project
    @projects = query.includes(:feature_projects, :features, :stories, :tasks).in_name_order('ASC')
  end

  def ensure_features
    params[:project][:features] = Feature.find_all_by_id(params[:project][:features]) if params.present? && params[:project].present? && params[:project][:features].present?
  end

  def ensure_initial_state
    @edited = []
    @expanded = []
    @changed = []
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def feature_labels(feature_projects = [])
    feature_projects.map do |feature_project|
      status_tag feature_project.feature.name, feature_project.status
    end.join.html_safe
  end
  
end

app/views/projects/_edit.html.haml
- project ||= @project
- remote = false if remote.nil?
- stand_alone = true if stand_alone.nil?

= content_tag stand_alone ? 'div' : 'td', stand_alone ? {class: 'project expanded'} : {colspan: 4} do
  = form_for project, remote:remote do |f|
    .row-fluid
      .span12
        - if project.errors.any?
          .row-fluid
            .span12
              #error_explanation
                %h2= "#{pluralize(project.errors.count, "error")} prohibited this project from being saved:"
                %ul
                  - project.errors.full_messages.each do |msg|
                    %li= msg

        .row-fluid.section
          .span6
            = f.label :name
            = f.text_field :name, class: 'span12'
          .span3
            = f.label :start_date
            = f.text_field :start_date, data: {datefield: true}, class: 'span12'
          .span3
            = f.label :end_date
            = f.text_field :end_date, data: {datefield: true}, class: 'span12'
        
        .row-fluid.section
          .span12
            - project.feature_projects.in_feature_order.each_slice(4) do |feature_projects|
              .row-fluid
                .span12
                  .features= render partial: 'feature_project', collection: feature_projects

        .row-fluid
          .span4.offset8.text-right
            = f.submit 'Save', class: 'btn btn-small btn-flat btn-primary'
            \|
            - if can? :destroy, project
              = link_to 'Delete', project, method: :delete, data:{confirm: "WARNING: Are you sure you want to delete this project?" }, remote:remote, class: 'btn btn-small btn-flat btn-danger'
              \|
            = link_to 'Cancel', project.new_record? ? projects_path : project_path(project), remote:remote, class: 'btn btn-small btn-flat btn-link'
  = render template: 'shared/bind_dates'

app/views/projects/_feature_project.html.haml
.span3
  = label_tag "project_feature_projects_#{feature_project.id}" do
    .feature
      = hidden_field_tag "project[feature_projects_attributes][#{feature_project.id}][id]", feature_project.id
      = hidden_field_tag "project[feature_projects_attributes][#{feature_project.id}][feature_id]", feature_project.feature_id
      = hidden_field_tag "project[feature_projects_attributes][#{feature_project.id}][project_id]", feature_project.project_id
      - FeatureProject::ALL_STATES_UI_ORDERED.each do |state|
        %span{data: {status: state}}
          = radio_button_tag "project[feature_projects_attributes][#{feature_project.id}][status]", state, feature_project.status == state, {data: {status: state}}
          %i{class: "#{state} #{status_to_classes(state)} #{feature_project.in_state?(state) ? 'active' : nil}"}
    = feature_project.feature.name

app/views/projects/_project.html.haml
- edited ||= []
- expanded ||= []
- project ||= @project
- id = project.new_record? ? 'new' : project.id

- if edited.include?(id)
  %li.project.edit-mode.expanded#Project{id: id, data: {expanded: 1}}
    = render partial: 'edit', locals:{project:project, remote:true, stand_alone:false}

- else
  %li.project#Project{id: id}
    = render partial: 'show', locals:{project:project, remote:true, stand_alone:false}

app/views/projects/_projects.html.haml
#Main
  = render 'layouts/messages'
  = render 'shared/overview'

  %ol.unstyled.project-list#ProjectList
    - if @projects.empty?
      %li.project#Project_new{data: {empty: 1}}
        %h3.subheader= t(:none_html, scope: [:controllers, :projects])
    - else
      = render partial: 'project', collection: @projects, locals: {edited: @edited, expanded: @expanded}

app/views/projects/_show.html.haml
- project ||= @project
- remote = false if remote.nil?
- stand_alone = true if stand_alone.nil?

- if stand_alone
  .project.expanded
    %form
      .row-fluid.section
        .span7
          %label= 'Name'
          .title= project.name
      .row-fluid.section
        .span12
          %label= 'Features'
          .features= feature_labels(project.feature_projects.in_feature_order)
      .row-fluid
        .span4.offset8.text-right
          - if can? :edit, project
            = link_to 'Edit', edit_project_path(project), remote:remote, class: 'btn btn-small btn-flat btn-primary'
            \|
          - if can? :destroy, project
            = link_to 'Delete', project, method: :delete, data: { confirm: "WARNING: Are you sure you want to delete this project?" }, remote:remote, class: 'btn btn-small btn-flat btn-danger'
            \|
          = link_to 'Back', projects_path, class: 'btn btn-small btn-flat btn-link'

- else
  .project.expanded
    %form
      .row-fluid.section
        .span7
          %label= 'Name'
          .title= project.name
      .row-fluid.section
        .span12
          %label= 'Features'
          .features= feature_labels(project.feature_projects.in_feature_order)
          .command-block.on-hover<
            - if can? :edit, project
              = awesome_link_to '', edit_project_path(project), glyph: 'awesome-edit', remote:true

app/views/projects/delete.js.erb
$('#Project_<%= @project.id%>').remove();
<%= render template: 'shared/messages' unless flash.empty? %>
<%= render template: 'shared/reset_transients' %>

app/views/projects/project.js.erb
<%
content = escape_javascript(render(partial: @project, locals: {edited: @edited, expanded: @expanded}))
id = @project.new_record? ? 'new' : @project.id
%>
if ($('#Project_<%= id %>').length > 0) {
  $('#Project_<%= id%>').replaceWith('<%= content %>');
} else if ($('ol.project-list > li').length > 0) {
  $('ol.project-list > li').first().before('<%= content %>');
  $('ol.project-list > li[data-empty]').remove();
}
<% if @changed.include?(id) %>
$('#Project_<%= id%>').effect('highlight',{duration: 750});
<% end %>
<%= render 'shared/messages' unless flash.empty? %>
<%= render 'shared/reset_transients' %>