config/routes.rb
class TaskPointConstraint
  def matches?(request)
    points = request.query_parameters['points']
    (points.blank? || points =~ /^\d+$/)
  end
end

class TaskRankConstraint
  def matches?(request)
    before = request.query_parameters['before']
    after = request.query_parameters['after']
    (before.blank? || before =~ /^\d+$/) && (after.blank? || after =~ /^\d+$/)
  end
end

Tracker::Application.routes.draw do
  devise_for :users

  root to: 'tasks#index'

  resources :features

  resources :projects do
    delete :index, on: :collection
  end

  resources :reference_types
  
  
  resources :stories do
    delete :index, on: :collection
  end

  resources :tasks do
    collection do
      delete :index
      get :print
    end
    member do
      post :advance
      post :block
      post :complete
      post :point, constraints: TaskPointConstraint.new
      post :rank, constraints: TaskRankConstraint.new
      post :unblock
    end
  end

  resources :teams

  resources :users
  
  resources :test if Rails.is_test?

end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id           :integer          not null, primary key
#  release_date :datetime
#  title        :string(255)
#  feature_id   :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  date_status  :string(255)      default("planned")
#

class Story < ActiveRecord::Base
  include CacheCleanser
  include StatusScopes

  DATE_STATES = ['planned', 'estimated', 'unknown']

  attr_accessor :create_tasks
  attr_accessible :create_tasks, :references, :references_attributes, :release_date, :release_date_status, :feature_id, :tag_list, :title

  acts_as_taggable

  after_initialize :initialize_create_tasks
  before_validation :ensure_release_date_status
  after_save :ensure_tasks
  
  belongs_to :feature
  has_many :tasks, dependent: :destroy
  has_many :projects, through: :tasks
  has_many :referent_references, as: :referent, dependent: :destroy
  has_many :references, through: :referent_references

  accepts_nested_attributes_for :references, allow_destroy: true
  
  validates_presence_of :feature, :title
  validates_inclusion_of :release_date_status, in: DATE_STATES

  scope :has_tasks_in_state, lambda{|status| where('(SELECT COUNT(*) FROM tasks WHERE tasks.story_id = stories.id AND tasks.status IN (?)) > 0', status)}
  scope :has_tasks_in_state_for_projects, lambda{|status, projects| where('(SELECT COUNT(*) FROM tasks WHERE tasks.story_id = stories.id AND tasks.status IN (?) AND tasks.project_id IN (?)) > 0', status, projects)}

  scope :for_features, lambda{|features| where(feature_id: features)}
  scope :for_projects, lambda{|projects| joins(:tasks).where(tasks: {project_id: projects})}
  
  scope :on_or_after_date, lambda{|date| where('release_date >= ?', date)}
  scope :on_or_before_date, lambda{|date| where('release_date <= ?', date)}
  scope :on_date, lambda{|date| where('release_date = ?', date)}
  
  scope :in_date_order, lambda{|dir = 'ASC'| order("release_date #{dir}")}
  scope :in_feature_order, lambda{|dir = 'ASC'| joins(:feature).order("features.name #{dir}")}
  scope :in_reference_order, lambda{|dir = 'ASC'| order("CAST(references.value AS UNSIGNED) #{dir}")}
  scope :in_title_order, lambda{|dir = 'ASC'| order("stories.title #{dir}")}
  
  class<<self
    def all_date_states
      @all_states ||= Story::DATE_STATES.map{|s| [s.humanize, s]}
    end

    def all_stories
      @all_stories ||= [['-', '']] + Story.in_title_order.map{|s| [ s.to_s, s.id ] }
    end
    
    def refresh_cache
      @all_stories = nil
    end
  end

  def to_s
    s = self.title
    s += " (#{self.feature.name})" if self.feature.present?
    s += " - #{self.release_date.to_date.to_s(:yy_mm_dd)}" if self.release_date.present?
    s
  end
  
  private
  
  def initialize_create_tasks
    self.create_tasks ||= true
  end

  def ensure_release_date_status
    self.release_date_status = 'planned' if self.release_date_status.nil? && self.release_date.present?
  end
  
  def ensure_tasks
    return unless self.create_tasks
    Task.ensure_story_tasks(self)
  end
  
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  include FilterHandler
  include ReferencesHandler
  include SortHandler

  DEFAULT_SORT = ['date']
  SORT_FIELDS = ['date', 'feature', 'reference', 'title']
  INDEX_ACTIONS = [:create, :destroy, :index, :update]

  load_and_authorize_resource

  before_filter :ensure_initial_state
  before_filter :build_index_query, only: INDEX_ACTIONS
  
  # GET /stories
  # GET /stories.json
  def index
    respond_to do |format|
      format.html { render 'shared/index' }
      format.js { render @filter.errors.empty? ? 'shared/index' : 'filter'; flash.discard }
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @expanded << @story.id if params.has_key?(:expanded)

    respond_to do |format|
      format.html { render template: 'shared/show' }
      format.js { render 'story'; flash.discard }
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @edited << 'new'
    @expanded << 'new'

    respond_to do |format|
      format.html { render template: 'shared/new' }
      format.js { render 'story'; flash.discard }
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @edited << @story.id
    @expanded << @story.id

    respond_to do |format|
      format.html { render template: 'shared/edit' }
      format.js { render 'story'; flash.discard }
      format.json { render json: @story }
    end
  end

  # POST /stories
  # POST /stories.json
  def create
    respond_to do |format|
      if @story.save
        flash[:notice] = 'Story was successfully created.'
        @changed << @story.id

        format.html { redirect_to stories_path }
        format.js { render 'shared/index'; flash.discard }
        format.json { render json: @story, status: :created, location: @story }
      else
        @edited << 'new'
        @expanded << 'new'

        format.html { render action: 'new', template: 'shared/new' }
        format.js { render 'story'; flash.discard }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update_attributes(params[:story])
        flash[:notice] = 'Story was successfully updated.'
        @changed << @story.id
        
        format.html { redirect_to stories_path }
        format.js { render 'shared/index'; flash.discard }
        format.json { head :no_content }
      else
        @edited << @story.id
        @expanded << @story.id

        format.html { render action: 'edit', template: 'shared/edit' }
        format.js { render 'story'; flash.discard }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy

    flash[:notice] = 'Story was successfully deleted.'

    respond_to do |format|
      format.html { redirect_to stories_path }
      format.js { render 'shared/index'; flash.discard }
      format.json { head :no_content }
    end
  end

  def is_index_action
    INDEX_ACTIONS.include?(action_name.to_sym)
  end

  private

  def build_index_query
    query = @stories || Story

    contact_us = @filter.content[:contact_us]
    projects = @filter.content[:projects]
    features = @filter.content[:features]
    status = @filter.content[:status]

    if status.present?
      query = projects.present? ? query.has_tasks_in_state_for_projects(status, projects) : query.has_tasks_in_state(status)
    end

    query = query.for_contact_us(contact_us) if contact_us.present?
    query = query.for_features(features) if features.present?
    query = query.for_projects(projects) if projects.present?

    query = query.on_or_after_date(@filter.content[:after]) if @filter.content[:after].present?
    query = query.on_or_before_date(@filter.content[:before]) if @filter.content[:before].present?
    
    @sort.each do |sort|
      case sort
      when '-date' then query = query.in_date_order('DESC')
      when 'date' then query = query.in_date_order('ASC')
      when '-feature' then query = query.in_feature_order('DESC')
      when 'feature' then query = query.in_feature_order('ASC')
      when '-reference' then query = query.in_reference_order('DESC')
      when 'reference' then query = query.in_reference_order('ASC')
      when '-title' then query = query.in_title_order('DESC')
      when 'title' then query = query.in_title_order('ASC')
      end
    end

    @stories = query.includes(:feature, :references, :tasks).uniq
  end

  def ensure_initial_state
    @edited = []
    @expanded = []
    @changed = []
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
  
  def story_project_labels(story, only_projects = [])
    projects = Project.active.map do |project|
            next unless only_projects.blank? || only_projects.include?(project.id)
            task = story.tasks.map{|task| task.project_id == project.id ? task : nil}.compact.sort{|task1, task2| task1.status <=> task2.status}.last
            status_tag project.name, (task.present? && task.status) || 'unsupported'
          end.join.html_safe
    link_to projects, tasks_path(filter: {content:{stories: story.id, projects: only_projects}})
  end
  
end

app/views/stories/_edit.html.haml
- remote = false if remote.nil?
- stand_alone = true if stand_alone.nil?
- story ||= @story

= content_tag stand_alone ? 'div' : 'td', stand_alone ? {class: 'story expanded'} : {colspan: 5} do
  = form_for story, remote:remote  do |f|
    .row-fluid
      .span12
        - if story.errors.any?
          .row-fluid
            .span12
              #error_explanation
                %h2= "#{pluralize(story.errors.count, "error")} prohibited this story from being saved:"
                %ul
                  - story.errors.full_messages.each do |msg|
                    %li= msg

        .row-fluid.section
          .span9
            = f.label :title
            = f.text_field :title, class: 'span12', autofocus: true
          .span3.projects
            = story_project_labels(story)
            = f.label :create_tasks, {} do
              = f.check_box :create_tasks
              = I18n.t(:create_tasks, scope: [:activerecord, :labels, :story])
        
        .row-fluid
          .span3  
            = f.label :feature_id
            = flat_select_tag 'story[feature_id]', options_for_select(Feature.active.map{|f| [ f.name, f.id ]}, story.feature_id)
          .span3
            = f.label :release_date
            = f.text_field :release_date, data: {datefield: true}, class: 'span12', type: 'datetime'
          .span3
            = f.label :release_date_status
            = flat_select_tag 'story[release_date_status]', options_for_select(Story::DATE_STATES.map{|t| [I18n.t(t, scope: [:activerecord, :labels, :story]), t]}, story.release_date_status), {data: {status_select: true}}

        / .row-fluid.section
        /   .span9
        /     = f.label :tag_list, t(:tag_list, scope: [:activerecord, :attributes, :story])
        /     = f.text_field :tag_list, class: 'span12'

        .row-fluid.section
          .span12
            = render partial: 'shared/edit_references', locals: {references: story.references, referent_type: :story}

        .row-fluid
          .span6.offset6.text-right
            = f.submit 'Save', class: 'btn btn-small btn-flat btn-primary'
            \|
            - if can? :edit, story
              - unless story.new_record?
                = link_to 'Delete', story, method: :delete, class: 'btn btn-small btn-flat btn-danger', data: { confirm: "WARNING: Are you sure you want to delete this story?" }, remote:remote
                \|
            = link_to 'Cancel', story.new_record? ? stories_path : story_path(story), class: 'btn btn-small btn-link', remote:remote
        = render template: 'shared/bind_dates'

app/views/stories/_filter.html.haml
- content = @filter.content || {}
- classes = []
- classes << 'visible' if !@filter.errors.empty? || params[:show]

#Filter{data: {filter: 1}, class: classes}
  .filter-container
    = form_for @filter, url: stories_path, method: :get, remote: true do |f|
      = f.hidden_field :id
      = f.hidden_field :area

      - if @filter.errors.any?
        .row-fluid
          .span12
            #error_explanation
              %h2= "#{pluralize(@filter.errors.count, "error")} prohibited this filter from being saved:"
              %ul
                - @filter.errors.full_messages.each do |msg|
                  %li= msg
      .row-fluid.section
        .span12
          = f.label :name
          = f.text_field :name, class: 'span8'
      
      .row-fluid.section
        .controls.controls-row
          .span2.multi-select
            = label_tag 'status', 'Status'
            = select_tag 'filter[content][status]', options_for_select(StatusScopes.all_states, content[:status]), multiple: true, class: 'span12'
          .span3.multi-select
            = label_tag 'projects', 'Projects'
            = select_tag 'filter[content][projects]', options_for_select(Project.all_projects, content[:projects]), multiple: true, class: 'span12'
          .span3.multi-select
            = label_tag 'features', 'Features'
            = select_tag 'filter[content][features]', options_for_select(Feature.all_features, content[:features]), multiple: true, class: 'span12'
          .span4
            .row-fluid
              .span5
                = label_tag 'after', 'Due on or After'
                = text_field_tag 'filter[content][after]', content[:after], data: {datefield: true}
            .row-fluid
              .span5
                = label_tag 'after', 'Due on or Before'
                = text_field_tag 'filter[content][before]', content[:before], data: {datefield: true}
      
      .row-fluid.section
        .span4.offset8.text-right
          = submit_tag 'Apply', name: :apply, class: 'btn btn-small btn-flat btn-primary'
          - if @filter.new_record?
            \|
            = submit_tag 'Save', name: :commit_filter, class: 'btn btn-small btn-flat btn-info'
          - else
            \|
            = submit_tag 'Update', name: :commit_filter, class: 'btn btn-small btn-flat btn-info'
            \|
            = link_to 'Delete', stories_path(destroy: true), method: :delete, data: { confirm: "#{t(:warning_html, scope: :filter)}" }, remote: true, class: 'btn btn-small btn-flat btn-danger'
          \|
          = link_to 'Close', 'javascript:void();', data: {filter_close: true}, class: 'btn btn-small btn-link'
  = render template: 'shared/bind_dates'

app/views/stories/_form.html.haml
- options= {'controller' => controller.controller_name}
- options['action'] = @story.new_record? ? :create : :update
- options['id'] = @story.id unless @story.new_record?
- @story.release_date = @story.release_date.to_date if @story.release_date.present? && @story.release_date.acts_like?(:time)

= form_for @story, url: url_for(options)  do |f|
  - if @story.errors.any?
    #error_explanation
      %h2= "#{pluralize(@story.errors.count, "error")} prohibited this story from being saved:"
      %ul
        - @story.errors.full_messages.each do |msg|
          %li= msg

  .row
    .six.columns.end
      = f.label :title
      = f.text_field :title, size: 25
  .row
    .two.columns
      = f.label :service_id
      = f.select :service_id, Service.active.map{|s| [ s.abbreviation, s.id ] }
    .two.column
      = f.label :contact_us_number, I18n.t(:contact_us_number, scope: [:activerecord, :attributes, :story])
      = f.text_field :contact_us_number, size: 5
    .two.columns.end
      = f.label :release_date
      = f.text_field :release_date, data: {datefield: true}
  .row
    = f.label :create_tasks, {} do
      = f.check_box :create_tasks
      = I18n.t(:create_tasks, scope: [:activerecord, :labels, :story])
  .row
    .actions
      = f.submit 'Save'
      \|
      = link_to 'Delete', @story, method: :delete, data: { confirm: "WARNING: Are you sure you want to delete this story?" }
      \|
      = link_to 'Cancel', :back

app/views/stories/_references.html.haml
- story ||= @story
- story.references.each do |reference|
  .row-fluid
    .span12
      - if reference.linkable?
        %a{href: reference.url_for}= reference
      - else
        = reference

app/views/stories/_show.html.haml
- story ||= @story
- remote = false if remote.nil?
- stand_alone = true if stand_alone.nil?

- if stand_alone
  .story.expanded
    %form
      .row-fluid.section
        .span9
          %label= 'Title'
          .title= @story.title
        .span3
          %label= 'Projects'
          .projects= story_project_labels(@story)
      .row-fluid.section
        .span2
          %label= 'Feature'
          = @story.feature.name if @story.feature.present?
        .span4
          %label= 'Release Date'
          - if @story.release_date.present?
            %span{data: {date_status: @story.release_date_status}}
              = @story.release_date.to_date.to_s(:yy_mm_dd)
              = " (#{@story.release_date_status.humanize})"

      / - if story.tag_list.present?
      /   .row-fluid.section
      /     .span12
      /       %label= 'Tags'
      /       .tags= story.tag_list
      - if story.references.present?
        .row-fluid.section
          .span9
            %label= 'References'
            = render partial: 'shared/show_references', locals:{references: story.references}
      .row-fluid
        .span4.offset8.text-right
          - if can? :edit, story
            = link_to 'Edit', edit_story_path(@story), remote:remote, class: 'btn btn-small btn-flat btn-primary'
            \|
          - if can? :destroy, story
            = link_to 'Delete', @story, method: :delete, data: { confirm: "WARNING: Are you sure you want to delete this story?" }, remote:remote, class: 'btn btn-small btn-flat btn-danger'
            \|
          = link_to 'Back', :back, class: 'btn btn-small btn-link'

- else
  %td.span2= story.title
  %td.span1= story.feature.name if story.feature.present?
  %td.span2
    %span{data: {date_status: story.release_date_status}}
      = story.release_date.in_time_zone.to_date.to_s(:yy_mm_dd) if story.release_date.present?
  %td.span2= render partial: 'shared/show_references', locals:{references: story.references}
  %td.span2
    = story_project_labels(story, (@filter.present? ? @filter.content : {})[:projects])
    .command-block.on-hover<
      - if can? :edit, story
        = awesome_link_to '', edit_story_path(story), glyph: 'awesome-edit', remote:true

app/views/stories/_stories.html.haml
#Main
  = render 'layouts/messages'
  = render 'shared/overview'

  %table.table.story-list#StoryList
    %thead
      %tr
        = render partial: 'shared/sortable', locals: {name: 'Title', field: 'title', classes: 'span2'}
        = render partial: 'shared/sortable', locals: {name: 'Feature', field: 'feature', classes: 'span1'}
        = render partial: 'shared/sortable', locals: {name: 'Release Date', field: 'date', classes: 'span1'}
        = render partial: 'shared/sortable', locals: {name: 'References', field: 'reference', classes: 'span2'}
        %th.three.span2 Projects

    %tbody
      - if @stories.empty?
        %tr.story.expanded#Story_new{data: {empty: 1}}
          %td{colspan: 5}
            %h3.subheader= t(:none_html, scope: [:controllers, :stories])
      - else
        = render partial: 'story', collection: @stories, locals: {edited: @edited, expanded: @expanded}

app/views/stories/_story.html.haml
- edited ||= []
- expanded ||= []
- story ||= @story
- id = story.new_record? ? 'new' : story.id

- if edited.include?(id)
  %tr.story.edit-mode.expanded#Story{id: id, data: {expanded: 1}}
    = render partial: 'edit', locals:{story:story, remote:true, stand_alone:false}

- else
  %tr.story.compact#Story{id: id}
    = render partial: 'show', locals:{story:story, remote:true, stand_alone:false}

app/views/stories/delete.js.erb
$('#Story_<%= @story.id%>').remove();
<%= render template: 'shared/messages' unless flash.empty? %>
<%= render template: 'shared/reset_transients' %>

app/views/stories/story.js.erb
<%
content = escape_javascript(render(partial: @story, locals: {edited: @edited, expanded: @expanded}))
id = @story.new_record? ? 'new' : @story.id
%>
if ($('#Story_<%= id %>').length > 0) {
  $('#Story_<%= id%>').replaceWith('<%= content %>');
} else if ($('.story-list > tbody > tr').length > 0) {
  $('.story-list > tbody > tr').first().before('<%= content %>');
  $('.story-list > tbody > tr[data-empty]').remove();
}
<% if @changed.include?(id) %>
$('#Story_<%= id%>').effect('highlight',{duration: 750});
<% end %>
<%= render 'shared/messages' unless flash.empty? %>
<%= render 'shared/reset_transients' %>